# 禁用 ForgeGradle 的 SSL 证书检查
org.gradle.jvmargs=-Xmx3G -Dnet.minecraftforge.gradle.check.certs=false

# 构建性能
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# ------------------ 环境版本 ------------------
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)

# ------------------ Parchment 映射 ------------------
parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03-1.20.1

# ------------------ 模组信息 ------------------
mod_id=create_hand_made
mod_name=Create: Hand Made
mod_license=MIT
mod_version=0.2.0-beta
mod_group_id=com.alben.createhandmade

# ------------------ Create 及其附属依赖 ------------------
create_version=6.0.8-289
create_mod_version=6.0.8
ponder_version=1.0.91
flywheel_version=1.0.5
registrate_version=MC1.20-1.3.3

# ------------------ JEI ------------------
jei_version=15.20.0.106

# -----------------KubeJS------------------
kubejs_version=2001.6.5-build.26

# KubeJS 的 Rhino 依赖
rhino_version=2001.2.2-build.11

#-------------------版本-------------------
mapping_channel=official
mapping_version=1.20.1