modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="alben"
description='''
A Create addon for hand crafting.
'''
logoFile="mod_logo.png"

[[mixins]]
config="${mod_id}.mixins.json"

# ==================== Forge 依赖 ====================
# ★ NeoForge → Forge
# ★ type="required" → mandatory=true
# ★ type="optional" → mandatory=false

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
mandatory=true
versionRange="[${create_mod_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
mandatory=false
versionRange="[${jei_version},)"
ordering="NONE"
side="BOTH"